alias dp="bash ${HOME}/.dotfiles/scripts/dev/push_dotfiles.sh"
alias sp="bash $HOME/.dotfiles/rime/push"
alias rp="realpath"
alias ea="nvim ${HOME}/.dotfiles/aliases.conf"

alias extract="bash ${HOME}/.dotfiles/scripts/utils/extract.sh"
alias random:string="bash ${HOME}/.dotfiles/scripts/utils/random_string.sh"
alias git:clean="bash ${HOME}/.dotfiles/scripts/dev/git_clean.sh"

alias backup:config="bash ${HOME}/.dotfiles/scripts/system/backup_config.sh"
alias disk:usage="bash ${HOME}/.dotfiles/scripts/system/disk_usage.sh"
alias find:large="bash ${HOME}/.dotfiles/scripts/system/find_large_files.sh"
alias port:check="bash ${HOME}/.dotfiles/scripts/system/port_check.sh"
