# Ranger config

# 快速连接提示
alias alpine echo "sftp://student@localhost:2222 (密码: student)"

# 设置编辑器
set preview_images true
set draw_borders both

# icon plugins
default_linemode devicons
set show_hidden true
set preview_files true

# 使用 LazyVim (nvim) 打开文件
map <C-o> shell nvim "$@"

# Archives plugin shortcuts
map ex extract
map ec compress
