# Ranger config

# 快速连接提示
alias alpine echo "sftp://student@localhost:2222 (密码: student)"

# 设置编辑器
set preview_images true
set draw_borders both

# icon plugins
default_linemode devicons
set show_hidden true
set preview_files true

# Archives plugin shortcuts
map ex extract
map ec compress
