# Vertical Candidate List
Vertical Candidate List=True
# Use Per Screen DPI
PerScreenDPI=True
# Use Input Method Langauge To Decide Font
UseInputMethodLangaugeToDecideFont=True
# Theme
Theme=default-dark
